# Generated by Django 4.1.1 on 2022-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaling',
            options={'verbose_name_plural': 'Journaling'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='rec',
            options={'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AddField(
            model_name='rec',
            name='choices',
            field=models.CharField(blank=True, choices=[('song', 'song'), ('movie', 'movie'), ('tvShow', 'tvShow'), ('podcast', 'podcast'), ('book', 'book')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rec',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
