# Generated by Django 4.1.2 on 2022-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_link_rec_platform_blog_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
