# Generated by Django 4.0.6 on 2022-10-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rec_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='therapy',
            name='choices',
            field=models.CharField(blank=True, choices=[('1k', 'Below 1000'), ('1k-3k', '1000-3000'), ('3k-5k', '3000-5000'), ('5k', 'Above 5000')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='therapy',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
