# Generated by Django 4.0.6 on 2022-10-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_therapy_age_therapy_choices_therapy_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journaling',
            old_name='cmpname',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='journaling',
            old_name='position',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='journaling',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='journaling',
            name='shortdescription',
        ),
        migrations.RemoveField(
            model_name='journaling',
            name='updatedat',
        ),
        migrations.AddField(
            model_name='journaling',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
